@extends('template')
    @section('title')
     {{$post}}   
    @endsection
    @section('content')
        <h1>{{$post->title}}</h1>
        <p>
            {{$post->body}}
        </p>
    @endsection